feat: upgraded web3py.
Previous code worked up to web3==3.6.1

From 3.7.0 on, we'd get the following error when running ETH tests:

```
venv/lib/python3.10/site-packages/hexbytes/_utils.py:54: Error
```

That's because casting `HexBytes` objects to string using `str()` would
not result in a 0xstring anymore:

```
>>> str(HexBytes('0x88f3a800a5455bca864ec026bd7bef1a2af1e741f6c635f47783032b838e54dd'))
b'C\x83F\x8a\xb5\xbb\xafxE\x12\xb44\xc5\x0f\x8ez\xbe<\xbe]\xaf\xb2\x8er\xa5\xfc-j\xdb\xff\xbc\xd6'
```

Which would then break when calling:

```
interface.decode_function_input(call.metadata['input'])
```

The fix is to use `HexBytes.hex` to cast it to the expected value.