feat: support for pytezos 3.10+.
The Nairobi protol updated its reveal gas prices:

https://tezos.gitlab.io/protocols/017_nairobi.html#breaking-changes

Pytezos now implements these new gas prices:

https://github.com/baking-bad/pytezos/blob/fb1036af30f6268755d3dbe1eb6ee6703cdefa34/src/pytezos/operation/fees.py#L69

As such, running Pytezos 3.10.0 on sandboxes with protocols older than
Nairobi result in gas exhaustion errors when revealing:

```
src/djwebdapp_tezos/provider.py:301: in deploy
    self.client.reveal().send(min_confirmations=1)

...

pytezos.rpc.node.RpcError: ({'id': 'proto.015-PtLimaPt.gas_exhausted.operation', 'kind': 'temporary'},)
```

Thus the sandbox was upgraded to pass the tests in CI.